export const MENU_CACHE_S_MAXAGE_SECONDS = 300;
export const MENU_CACHE_STALE_WHILE_REVALIDATE_SECONDS = 60;
export const MENU_AVAILABILITY_S_MAXAGE_SECONDS = 5;

export const MENU_CACHE_CONTROL = `public, s-maxage=${MENU_CACHE_S_MAXAGE_SECONDS.toString()}, stale-while-revalidate=${MENU_CACHE_STALE_WHILE_REVALIDATE_SECONDS.toString()}`;

export const MENU_AVAILABILITY_CACHE_CONTROL = `public, s-maxage=${MENU_AVAILABILITY_S_MAXAGE_SECONDS.toString()}`;
