import { sql } from 'drizzle-orm';
import { foreignKey, timestamp, uniqueIndex, uuid, type PgColumn } from 'drizzle-orm/pg-core';

/**
 * Standard primary key. UUID v4 generated by Postgres (`gen_random_uuid()`
 * from the `pgcrypto` extension). Never expose database-internal sequences
 * across the public API.
 */
export const pkUuid = () =>
  uuid('id')
    .primaryKey()
    .default(sql`gen_random_uuid()`);

/**
 * Tenant id column. Every domain table carries this column and every
 * index leads with it. RLS policies reference it via
 * `current_setting('app.current_tenant')::uuid`.
 *
 * NOTE: this helper does NOT declare the FK — each table builds its own
 * `tenants_tenant_fk` so the per-table `onDelete` is explicit at the
 * call site. Current convention across the schema is `onDelete: 'cascade'`,
 * which is consistent with the explicit `tenancy_erase_tenant` SQL
 * function being the authorised path for tenant data removal (live
 * deletes propagate; GDPR-class erasure is performed under
 * `withoutTenant` by that function).
 *
 * Historical doc claimed `onDelete: 'restrict'` here — that was the
 * stated intent but never the implementation. ADR-0020 tracks
 * standardising the FK behaviour as tech debt.
 */
export const tenantIdColumn = () => uuid('tenant_id').notNull();

/**
 * Standard audit timestamps applied to every domain table.
 *
 * - `created_at`: row creation; immutable.
 * - `updated_at`: last write; refreshed by application code on update.
 * - `archived_at`: soft-delete marker. We never hard-delete domain rows
 *   from production — preserve history for audit and rollback.
 */
export const timestampsColumns = () => ({
  createdAt: timestamp('created_at', { withTimezone: true, mode: 'date' })
    .notNull()
    .default(sql`now()`),
  updatedAt: timestamp('updated_at', { withTimezone: true, mode: 'date' })
    .notNull()
    .default(sql`now()`),
  archivedAt: timestamp('archived_at', { withTimezone: true, mode: 'date' }),
});

/**
 * ADR-0020 I-2: tenant-parent table exposes `UNIQUE (id, tenant_id)` so
 * child tables can declare composite FK `(parent_id, tenant_id) → parent(id, tenant_id)`.
 */
export const tenantParentUniqueIndex = (
  tableName: string,
  cols: { id: PgColumn; tenantId: PgColumn },
) => uniqueIndex(`${tableName}_id_tenant_uq`).on(cols.id, cols.tenantId);

/**
 * ADR-0020 I-2: composite FK on tenant-scoped child tables. Prevents
 * cross-tenant phantom rows via value-only `tenant_id` carry on join paths.
 */
export const compositeTenantFk = (params: {
  name: string;
  child: { id: PgColumn; tenantId: PgColumn };
  parent: { id: PgColumn; tenantId: PgColumn };
}) =>
  foreignKey({
    name: params.name,
    columns: [params.child.id, params.child.tenantId],
    foreignColumns: [params.parent.id, params.parent.tenantId],
  });
