import { sql } from 'drizzle-orm';
import { timestamp, uuid } from 'drizzle-orm/pg-core';

/**
 * Standard primary key. UUID v4 generated by Postgres (`gen_random_uuid()`
 * from the `pgcrypto` extension). Never expose database-internal sequences
 * across the public API.
 */
export const pkUuid = () =>
  uuid('id')
    .primaryKey()
    .default(sql`gen_random_uuid()`);

/**
 * Tenant foreign key. Every domain table carries this column and every
 * index leads with it. RLS policies reference it via
 * `current_setting('app.current_tenant')::uuid`.
 *
 * `onDelete: 'restrict'` — we do not delete tenants in place; archiving
 * sets `archived_at` and preserves history.
 */
export const tenantIdColumn = () => uuid('tenant_id').notNull();

/**
 * Standard audit timestamps applied to every domain table.
 *
 * - `created_at`: row creation; immutable.
 * - `updated_at`: last write; refreshed by application code on update.
 * - `archived_at`: soft-delete marker. We never hard-delete domain rows
 *   from production — preserve history for audit and rollback.
 */
export const timestampsColumns = () => ({
  createdAt: timestamp('created_at', { withTimezone: true, mode: 'date' })
    .notNull()
    .default(sql`now()`),
  updatedAt: timestamp('updated_at', { withTimezone: true, mode: 'date' })
    .notNull()
    .default(sql`now()`),
  archivedAt: timestamp('archived_at', { withTimezone: true, mode: 'date' }),
});
