import { z } from 'zod';
import { createZodDto } from 'nestjs-zod';
import {
  BrandContactsSchema,
  CountryCodeValue,
  CurrencyValue,
  LegalDocuments,
  LocalizedText,
  SocialLinksSchema,
  TenantSlugValue,
  TenantTheme,
} from '@resto/domain';
import type { TenantSnapshot } from '../../domain/tenant.aggregate';

const TenantResponseSchema = z.object({
  id: z.string().uuid(),
  slug: TenantSlugValue,
  displayName: z.string(),
  status: z.string(),
  locale: z.string(),
  contentLocales: z.array(z.string()),
  country: CountryCodeValue,
  defaultCurrency: CurrencyValue,
  theme: TenantTheme.nullable(),
  description: LocalizedText.nullable(),
  socials: SocialLinksSchema,
  legalDocuments: LegalDocuments.nullable(),
  contacts: BrandContactsSchema,
  legalName: z.string().nullable(),
  legalForm: z.enum(['IP', 'OOO', 'LLC', 'SOLE_PROP', 'OTHER']).nullable(),
  taxId: z.string().nullable(),
  paymentProvider: z.literal('stripe'),
  accountType: z.enum(['express', 'standard']).nullable(),
  stripeChargesEnabled: z.boolean(),
  stripePayoutsEnabled: z.boolean(),
  stripeOnboardingStatus: z.enum(['not_started', 'pending', 'complete', 'restricted']),
  stripeRequirementsDue: z.array(z.string()).nullable(),
  primaryDomain: z.string(),
  createdAt: z.string(),
  updatedAt: z.string(),
  archivedAt: z.string().nullable(),
  offboardingScheduledAt: z.string().nullable(),
  offboardingExecutedAt: z.string().nullable(),
  offboardingRequestedBy: z.string().nullable(),
});

export class TenantResponseDto extends createZodDto(TenantResponseSchema) {}
export type TenantResponse = z.infer<typeof TenantResponseSchema>;

export const toResponse = (s: TenantSnapshot): TenantResponse => ({
  id: s.id,
  slug: s.slug,
  displayName: s.displayName,
  status: s.status,
  locale: s.locale,
  contentLocales: [...s.contentLocales],
  country: s.country,
  defaultCurrency: s.defaultCurrency,
  theme: s.theme,
  description: s.description,
  socials: s.socials,
  legalDocuments: s.legalDocuments,
  contacts: s.contacts,
  legalName: s.legalName,
  legalForm: s.legalForm,
  taxId: s.taxId,
  paymentProvider: s.paymentProvider,
  accountType: s.accountType,
  stripeChargesEnabled: s.stripeChargesEnabled,
  stripePayoutsEnabled: s.stripePayoutsEnabled,
  stripeOnboardingStatus: s.stripeOnboardingStatus,
  stripeRequirementsDue: s.stripeRequirementsDue,
  primaryDomain: s.primaryDomain.domain,
  createdAt: s.createdAt.toISOString(),
  updatedAt: s.updatedAt.toISOString(),
  archivedAt: s.archivedAt?.toISOString() ?? null,
  offboardingScheduledAt: s.offboardingScheduledAt?.toISOString() ?? null,
  offboardingExecutedAt: s.offboardingExecutedAt?.toISOString() ?? null,
  offboardingRequestedBy: s.offboardingRequestedBy,
});
